
package com.siebel.customui;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite", targetNamespace = "http://siebel.com/CustomUI", wsdlLocation = "file:/C:/Users/ideyniy/IdeaProjects/SOGAZ_ESB/SiebelAdapter/src/main/resources/wsdl/siebelSR.wsdl")
public class SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service
    extends Service
{

    private final static URL SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_WSDL_LOCATION;
    private final static WebServiceException SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_EXCEPTION;
    private final static QName SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_QNAME = new QName("http://siebel.com/CustomUI", "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/ideyniy/IdeaProjects/SOGAZ_ESB/SiebelAdapter/src/main/resources/wsdl/siebelSR.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_WSDL_LOCATION = url;
        SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_EXCEPTION = e;
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service() {
        super(__getWsdlLocation(), SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_QNAME);
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_QNAME, features);
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service(URL wsdlLocation) {
        super(wsdlLocation, SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_QNAME);
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_QNAME, features);
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite
     */
    @WebEndpoint(name = "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite")
    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite getSGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite() {
        return super.getPort(new QName("http://siebel.com/CustomUI", "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite"), SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite
     */
    @WebEndpoint(name = "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite")
    public SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite getSGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite(WebServiceFeature... features) {
        return super.getPort(new QName("http://siebel.com/CustomUI", "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite"), SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_EXCEPTION!= null) {
            throw SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_EXCEPTION;
        }
        return SGZSPCSERVICESPCREQUESTSPCIMPORTSPCFROMSPCWEBSITE_WSDL_LOCATION;
    }

}
