
package com.siebel.customui;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SGZ_spcService_spcRequest_spcImport_spcFrom_spcWebsite", targetNamespace = "http://siebel.com/CustomUI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.customui.ObjectFactory.class,
    com.siebel.xml.sgz_20service_20request_20website.ObjectFactory.class
})
public interface SGZSpcServiceSpcRequestSpcImportSpcFromSpcWebsite {


    /**
     * 
     * @param importSRInput
     * @return
     *     returns com.siebel.customui.ImportSROutput
     */
    @WebMethod(operationName = "ImportSR", action = "document/http://siebel.com/CustomUI:ImportSR")
    @WebResult(name = "ImportSR_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "ImportSR_Output")
    public ImportSROutput importSR(
        @WebParam(name = "ImportSR_Input", targetNamespace = "http://siebel.com/CustomUI", partName = "ImportSR_Input")
        ImportSRInput importSRInput);

}
